import {
  getPlazaUseCount,
  listPublishedPlazaDesigns,
} from '../../shared/state/plazaPublishStore.js'
import { getSavedDesign } from '../../shared/state/savedDesignsStore.js'
import plazaMaster from '../../shared/data/plazaDesigns.json'
import { withBase } from '../../shared/assetUrl.js'

/** Design Plaza feed entries (real preview when `imageUrl` is set). */

export const HOME_PLAZA_SLOT_COUNT = 6

/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   tags: string,
 *   author: string,
 *   uses: string,
 *   useCount: number,
 *   imageUrl?: string,
 * }} PlazaPlaceholder
 */

/**
 * Master-table published rows (seed + synced UGC).
 * @returns {PlazaPlaceholder[]}
 */
function listMasterPublished() {
  return (plazaMaster.designs || [])
    .filter((d) => d.status === 'published')
    .map((d) => {
      const useCount = getPlazaUseCount(d.id, Number(d.use_count) || 0)
      return {
        id: d.id,
        title: d.title,
        tags: d.blurb || '',
        author: d.designer_name
          ? `@${String(d.designer_name).replace(/^@/, '')}`
          : '@designer',
        useCount,
        uses: `${useCount} 次使用`,
        imageUrl: d.image_path ? withBase(d.image_path) : undefined,
      }
    })
}

/**
 * Preview path from maintenance table (synced /plaza/*.png).
 * @param {string} id
 */
export function getMasterPlazaImagePath(id) {
  const row = (plazaMaster.designs || []).find((d) => d.id === id)
  const path = row?.image_path
  return typeof path === 'string' && path ? withBase(path) : ''
}

/**
 * Resolve preview for a publish: saved → publish snapshot → master table.
 * @param {{ id: string, sourceDesignId?: string, imageDataUrl?: string }} p
 */
export function resolvePlazaPreviewUrl(p) {
  const saved = p.sourceDesignId ? getSavedDesign(p.sourceDesignId) : null
  const raw =
    saved?.imageDataUrl ||
    p.imageDataUrl ||
    getMasterPlazaImagePath(p.id) ||
    ''
  return withBase(raw)
}
export function getSeedPlazaDesignRow(id) {
  return (plazaMaster.designs || []).find((d) => d.id === id && d.status === 'published') || null
}

/**
 * Adapt a master row to the same shape as user publishes (for details / use-design).
 * @param {string} id
 * @returns {import('../../shared/state/plazaPublishStore.js').PlazaPublishedDesign | null}
 */
export function getSeedPlazaAsPublished(id) {
  const d = getSeedPlazaDesignRow(id)
  if (!d) return null
  const name = String(d.designer_name || 'designer').replace(/^@/, '')
  const beadIds = String(d.bead_product_ids || '')
    .split('|')
    .map((s) => s.trim())
    .filter(Boolean)
  const beads = beadIds.map((productId, i) => ({
    instanceId: `seed-${d.id}-${i}`,
    productId,
  }))
  const baseCount = Number(d.use_count) || 0
  return {
    id: d.id,
    sourceDesignId: String(d.source_design_id || ''),
    title: d.title,
    author: `@${name}`,
    designerId: String(d.designer_id || ''),
    tags: d.blurb || '',
    usePriceTwd: Number(d.use_price_twd) || 0,
    publishedAt: Date.parse(String(d.published_at || '')) || 0,
    useCount: getPlazaUseCount(d.id, baseCount),
    beads,
    imageDataUrl: d.image_path ? withBase(d.image_path) : '',
  }
}

/**
 * Full plaza feed sorted by use count (desc). localStorage publishes win on id clash.
 * @returns {PlazaPlaceholder[]}
 */
export function listPlazaFeed() {
  /** @type {PlazaPlaceholder[]} */
  const published = listPublishedPlazaDesigns().map((p) => {
    const tags = isAutoGeneratedIntro(p.tags) ? '' : p.tags || ''
    const useCount = p.useCount || 0
    const imageUrl = resolvePlazaPreviewUrl(p) || undefined
    return {
      id: p.id,
      title: p.title,
      tags,
      author: p.author,
      useCount,
      uses: `${useCount} 次使用`,
      imageUrl,
    }
  })
  const localIds = new Set(published.map((p) => p.id))
  const fromMaster = listMasterPublished().filter((d) => !localIds.has(d.id))
  return [...published, ...fromMaster].sort((a, b) => {
    if (b.useCount !== a.useCount) return b.useCount - a.useCount
    return String(a.id).localeCompare(String(b.id))
  })
}

/** Legacy publishes filled tags with a price fallback when blurb was empty. */
function isAutoGeneratedIntro(tags) {
  return typeof tags === 'string' && tags.startsWith('原創設計')
}

/** Home grid: top N by use count. */
export function listHomePlazaFeed() {
  return listPlazaFeed().slice(0, HOME_PLAZA_SLOT_COUNT)
}

/** Shared “test photo” tile markup for banner / plaza image slots. */
export function testPhotoTile(extraClass = '') {
  return `<div class="flex h-full w-full items-center justify-center bg-stone-200 ${extraClass}">
    <span class="text-[0.65rem] text-stone-400">測試照片</span>
  </div>`
}

/**
 * Plaza / home card media: real preview when `imageUrl` is set, else test tile.
 * @param {PlazaPlaceholder} d
 * @param {string} [extraClass]
 */
export function plazaMediaTile(d, extraClass = '') {
  if (d.imageUrl) {
    return `<img src="${escapeAttr(d.imageUrl)}" alt="" draggable="false" class="pointer-events-none block h-full w-full select-none object-cover object-center ${extraClass}" />`
  }
  return testPhotoTile(extraClass)
}

/** @param {string} s */
function escapeAttr(s) {
  return String(s)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}
